### PR TITLE
feat: add oit section to about page

### PR DESCRIPTION
**Pull request by paulstey**
This is a baby PR that adds an OIT section to our `About` page. Kudos to @mcmcgrath13 for the help on the content!

### CODE REVIEW

**Comment by mcmcgrath13** [comment]
I'm not sure this makes sense as a top level section within About.  Should it go maybe as a section within the `mission`?

**Review by mirestrepo — APPROVED** [review]
❤️ 

@paulstey @mcmcgrath13 should there be a menu addition to the NavBar in the Nuxt repo for this section? (I'd vote for yes)

**Comment by mirestrepo** [comment]
`Our Teams` section could also be renamed to `Team Organization` or something along this lines and have OIT at the Top?

**Comment by mcmcgrath13** [comment]
> `Our Teams` section could also be renamed to `Team Organization` or something along this lines and have OIT at the Top?

Yes!

**Comment by mcmcgrath13** [comment]
I like the team organization solution.  If you really want this at the top level, make sure you also put in a PR over at the code repo so the sort order is correct.

**Comment by mirestrepo** [comment]
@paulstey you merged without combining into `Team Organization` section and moving that to top!?

**Pull request merged**
