### PR TITLE
fix: add question about brown network to fix storage app

### PR DESCRIPTION
**Pull request by paulstey**

### CODE REVIEW

**Comment by mcmcgrath13** [comment]
still broken 😢

**Comment by mirestrepo** [comment]
#59 fixes the storage app, not sure which branch should make PR where, but if you want me to change my PR to not be to main but rather to this branch I can do that

**Comment by mcmcgrath13** [comment]
I don't know if we need this question - I'm hesitant to have a question for everything possible as it gets unwieldy.  I think we already are pushing it and shout drop the replication question.

**Comment by mirestrepo** [comment]
I'd say the question is needed if it fundamentally changes the options. What storage options are `brown only`?

**Comment by mcmcgrath13** [comment]
maybe we need to figure out a way to make the questions more compact - the screen real estate for questions is a bit overwhelming

**Comment by mirestrepo** [comment]
I think this is stale. I'm closing but feel free to reopen if needed

**Pull request closed without merging**
