### PR TITLE
Feat collaborations joselynn

### PR DESCRIPTION
**Pull request by JRWallace**

### CODE REVIEW

**Review by mirestrepo — CHANGES_REQUESTED** [review]
This looks great! Thank you!!

You'll just need to update the schema for collaborations to include the new tags and 'groups'. If you expand on the failing validation, you'll see which ones are those. Let me know if it's not clear

**Comment by JRWallace** [comment]
> 

I think I fixed it, fingers crossed!

**Review by mirestrepo — APPROVED** [review]
🚀  Merge before someone merges to main again!

And just for next time, don't forget to request re-review, otherwise is kind of hard to notice when  a PR is ready again.

Thanks for doing this!

**Comment by JRWallace** [comment]
Oh, sorry -- I didn't realize but thank you!

**Pull request merged**
