### PR TITLE
added chai's profile

### PR DESCRIPTION
**Pull request by Equite774**
adding myself to the website

### CODE REVIEW

**Review by anna-murphy — APPROVED** [review]
Looks good! Great to have you on the team!

**Review by eldu — APPROVED** [review]
Looks great!

**Review by eldu — CHANGES_REQUESTED** [review]
seems like the tests aren't passing and this needs to be updated...

can you take a look?

**Comment by eldu** [comment]
I think chai is no longer an intern so i'm closing this PR. However, if it's not the case then submit a new one!

**Pull request closed without merging**
