### PR TITLE
Update facilities.md

### PR DESCRIPTION
**Pull request by rainxfan**
updated Vast Data sub-section

### CODE REVIEW

**Comment by rainxfan** [comment]
@yangliu2009 The Vast Data statement is updated .

**Comment by rainxfan** [comment]
In the facilities statement replaced:

> a GPFS parallel filesystem which provides a total of 3 - PB of usable storage space

with

> An all-flash parallel filesystem (Vast Data) that provides roughly 4 Petabytes of disk storage and is replicated to Brown University Disaster Recovery (DR) site. 
> a storage system which is ntegrated with the Hibernate backup/archival system

**Comment by yangliu2009** [comment]
Thank you for the changes, Rain. I just noticed a typo: "is ntegrated" should be "is integrated". Please correct that.

**Review by yangliu2009 — CHANGES_REQUESTED** [review]
Thank you for the changes, Rain. There is a tyop in line 23:  "ntegrated" should be "integrated". Please correct that.

**Comment by rainxfan** [comment]
updated a typo in line 23 "ntegrated" to "integrated"

**Review by yangliu2009 — CHANGES_REQUESTED** [review]
Hi Rain, please delete the session of Vast Data. Thanks.

**Review by yangliu2009 — APPROVED** [review]
LGTM. Thank you, Rain!

**Pull request merged**
